---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljc.
--- DateTime: 2020/6/29 19:18
---
--文件名为module.lua
--定义一个名为module的模块
module11 = {}

module11.aa = "aaaaa"
module1 = {}
--定义一个变量
module1.constant = "这是一个常量"

--定义一个函数
function module1.func1()
    io.write("这是一个公有函数!\n")
end


local function func2()
    print("这是一个私有函数!")
end

function module1.func3()
    func2()
end

return module1