---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljc.
--- DateTime: 2020/6/29 20:01
---
--获取get请求
--local getArgs = ngx.req.get_uri_args()
--for k, v in pairs(getArgs) do
--    ngx.say("GET Key:", k, " Value: ", v)
--    ngx.say("<br/>")
--    ngx.say("<br/>")
--end

--获取post请求
--ngx.req.read_body()
--local postArgs = ngx.req.get_post_args()
--for i, v in pairs(postArgs) do
--    ngx.say("POST Key: ", k, " Value: ", v)
--    ngx.say("<br/>")
--end



--编写Lua整合Redis脚本
--引入redis模块
local redis = require "resty.redis"
--创建一个redis实例
local red = redis:new()
--设置超时时间
red:set_timeout(5000)
--获取连接
local ok,err = red:connect("192.168.25.206", 6379)
if not ok then
   ngx.say("连接失败 ,,, ", err)
end

--如果有密码的需要加上密码验证
--写入redis数据
local ok, err = red:set("bigdata", "this is 1903")
if not ok then
    ngx.say("写入失败", err)
    return
end
ngx.say("写入成功", err)

--写入的时候可以控制连接池大小
local ok,err = red:set_keepalive(10, 5)
if not ok then
    ngx.say("failed to set keepalive", err)
    return
end